# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 4, 25, 16, 47, 4, 47240, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
