# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160426_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
